// AUTOGENERATED by Tools/generate_mtproxy_phase_classification.py - DO NOT EDIT.
// Source of truth: Tools/mtproxy_phase_contract.py. After editing the contract
// run the generator; check_mtproxy_all.py fails while this file is stale.
package org.telegram.messenger;

public final class ProxyPhaseClassification {

    private ProxyPhaseClassification() {
    }

    // Terminal verdicts that can be assigned before the socket performs any
    // real I/O (secret validation, DNS verdict caches, probe-coordinator
    // backoff decisions). deriveMtProxyTerminalDiagnostic must preserve these
    // across closeSocket: re-deriving from the startup timeline would replace
    // them with "connection_not_started", which is on the local-scheduler
    // skip list, so neither endpoint cooldown nor reconnect backoff would
    // engage and connect() would hot-loop.
    // Pass a ProxyCheckDiagnostics.normalize()d phase.
    public static boolean isPreIoTerminalVerdict(String phase) {
        if (phase == null) {
            return false;
        }
        switch (phase) {
            case "dns_negative_cache_hit":
            case "dns_blocked_zero_address":
            case "secret_parse_invalid_domain_control_char":
            case "secret_parse_invalid_domain":
            case "faketls_not_mtproxy_response":
            case "faketls_no_server_hello_terminal":
            case "faketls_server_closed_terminal":
            case "handshake_profiles_exhausted":
                return true;
            default:
                return false;
        }
    }

    // Failure verdicts that must hold the next reconnect attempt
    // (Connection::onDisconnectedInternal exponential backoff).
    // Pass a ProxyCheckDiagnostics.normalize()d phase.
    public static boolean needsReconnectBackoff(String phase) {
        if (phase == null) {
            return false;
        }
        switch (phase) {
            case "host_resolve_failed":
            case "host_resolve_timeout":
            case "tcp_not_connected":
            case "tcp_connection_refused":
            case "tcp_connect_timeout":
            case "tcp_connected_no_pong":
            case "secret_parse_invalid_domain_control_char":
            case "secret_parse_invalid_domain":
            case "faketls_not_mtproxy_response":
            case "faketls_no_server_hello_terminal":
            case "faketls_server_closed_terminal":
            case "handshake_profiles_exhausted":
            case "mtproxy_packet_sent_no_response":
            case "post_handshake_no_appdata":
            case "dropped_early_after_appdata":
                return true;
            default:
                return false;
        }
    }

    // Phases published through the MtProxySocketObservation facade
    // (mtProxySocketObservationIsHighRiskPhase): failures that must record
    // an endpoint failure at close, plus the data-path success markers
    // routed the same way.
    // Pass a ProxyCheckDiagnostics.normalize()d phase.
    public static boolean isObservationFacadePhase(String phase) {
        if (phase == null) {
            return false;
        }
        switch (phase) {
            case "first_tls_app_recv":
            case "first_mtproxy_packet_recv":
            case "dns_blocked_zero_address":
            case "secret_parse_invalid_domain_control_char":
            case "secret_parse_invalid_domain":
            case "faketls_not_mtproxy_response":
            case "faketls_no_server_hello_terminal":
            case "faketls_server_closed_terminal":
            case "handshake_profiles_exhausted":
            case "post_handshake_no_appdata":
            case "recipe_failed":
                return true;
            default:
                return false;
        }
    }

    // Local scheduler/gate timeouts: the wait was produced by our own
    // pre-TCP machinery (admission queue, endpoint cooldown, gates), not
    // by the network. MtProxyEndpointRecorder::recordFailure skips these so a local
    // wake-up never counts as an endpoint failure. Deliberately excludes
    // mtproxy_probe_wait_timeout and includes background_handshake_aborted.
    // Pass a ProxyCheckDiagnostics.normalize()d phase.
    public static boolean isLocalSchedulerTimeout(String phase) {
        if (phase == null) {
            return false;
        }
        switch (phase) {
            case "connection_not_started":
            case "admission_timeout":
            case "endpoint_cooldown_timeout":
            case "dns_coalesce_timeout":
            case "tcp_connect_gate_timeout":
            case "background_handshake_aborted":
                return true;
            default:
                return false;
        }
    }

    public static final int KIND_NEUTRAL = 0;
    public static final int KIND_LIVE = 1;
    public static final int KIND_SUCCESS = 2;
    public static final int KIND_FAILURE = 3;

    public static final int SCOPE_NONE = 0;
    public static final int SCOPE_EXACT = 1;
    public static final int SCOPE_NETWORK = 2;

    // Every phase the Java layer models. Unknown phases fall back to
    // ProxyPhasePolicy's conservative default (backoff-eligible exact
    // failure), matching the historical switch default.
    // Pass a ProxyCheckDiagnostics.normalize()d phase.
    public static boolean isKnownJavaPhase(String phase) {
        if (phase == null) {
            return false;
        }
        switch (phase) {
            case "ok":
            case "checking":
            case "cancelled":
            case "unknown_fail":
            case "admission_queue":
            case "endpoint_cooldown":
            case "tcp_connect_gate":
            case "dns_coalesce_wait":
            case "dns_cache_hit":
            case "dns_cache_store":
            case "mtproxy_probe_wait":
            case "phase_adaptive_recipe":
            case "secret_domain_sanitized":
            case "host_resolve_start":
            case "connect_start":
            case "socket_connect_start":
            case "socket_connected":
            case "client_hello_sent":
            case "admission_hold_after_client_hello_failure":
            case "server_hello_hmac_ok":
            case "on_connected":
            case "first_tls_app_sent":
            case "first_mtproxy_packet_sent":
            case "waiting_tcp":
            case "first_tls_app_recv":
            case "first_mtproxy_packet_recv":
            case "start_failed":
            case "connection_not_started":
            case "connecting_timeout":
            case "admission_timeout":
            case "endpoint_cooldown_timeout":
            case "mtproxy_probe_wait_timeout":
            case "dns_coalesce_timeout":
            case "dns_negative_cache_hit":
            case "dns_blocked_zero_address":
            case "host_resolve_failed":
            case "host_resolve_timeout":
            case "tcp_connect_gate_timeout":
            case "tcp_not_connected":
            case "tcp_connection_refused":
            case "tcp_connect_timeout":
            case "tcp_connected_no_pong":
            case "network_block_suspected":
            case "secret_parse_invalid_domain_control_char":
            case "secret_parse_invalid_domain":
            case "true_client_hello_timeout":
            case "faketls_server_hello_wait_timeout":
            case "server_closed_after_client_hello":
            case "client_hello_sent_no_server_hello":
            case "tls_alert_after_client_hello":
            case "short_tls_response_after_client_hello":
            case "unrecognized_response_after_client_hello":
            case "unrecognized_tls_response_after_client_hello":
            case "server_hello_hmac_mismatch":
            case "faketls_not_mtproxy_response":
            case "faketls_no_server_hello_terminal":
            case "faketls_server_closed_terminal":
            case "background_handshake_aborted":
            case "handshake_profiles_exhausted":
            case "mtproxy_packet_sent_no_response":
            case "post_handshake_no_appdata":
            case "dropped_early_after_appdata":
            case "dropped_after_appdata":
            case "shadowed_socket_failure":
            case "ignored_cancelled_generation":
                return true;
            default:
                return false;
        }
    }

    // Phase kind from the contract (kind= field).
    // Pass a ProxyCheckDiagnostics.normalize()d phase.
    public static int phaseKind(String phase) {
        if (phase == null) {
            return KIND_FAILURE;
        }
        switch (phase) {
            case "ok":
            case "checking":
            case "cancelled":
            case "shadowed_socket_failure":
            case "ignored_cancelled_generation":
                return KIND_NEUTRAL;
            case "admission_queue":
            case "endpoint_cooldown":
            case "tcp_connect_gate":
            case "dns_coalesce_wait":
            case "dns_cache_hit":
            case "dns_cache_store":
            case "mtproxy_probe_wait":
            case "phase_adaptive_recipe":
            case "secret_domain_sanitized":
            case "host_resolve_start":
            case "connect_start":
            case "socket_connect_start":
            case "socket_connected":
            case "client_hello_sent":
            case "admission_hold_after_client_hello_failure":
            case "server_hello_hmac_ok":
            case "on_connected":
            case "first_tls_app_sent":
            case "first_mtproxy_packet_sent":
            case "waiting_tcp":
                return KIND_LIVE;
            case "first_tls_app_recv":
            case "first_mtproxy_packet_recv":
                return KIND_SUCCESS;
            case "unknown_fail":
            case "start_failed":
            case "connection_not_started":
            case "connecting_timeout":
            case "admission_timeout":
            case "endpoint_cooldown_timeout":
            case "mtproxy_probe_wait_timeout":
            case "dns_coalesce_timeout":
            case "dns_negative_cache_hit":
            case "dns_blocked_zero_address":
            case "host_resolve_failed":
            case "host_resolve_timeout":
            case "tcp_connect_gate_timeout":
            case "tcp_not_connected":
            case "tcp_connection_refused":
            case "tcp_connect_timeout":
            case "tcp_connected_no_pong":
            case "network_block_suspected":
            case "secret_parse_invalid_domain_control_char":
            case "secret_parse_invalid_domain":
            case "true_client_hello_timeout":
            case "faketls_server_hello_wait_timeout":
            case "server_closed_after_client_hello":
            case "client_hello_sent_no_server_hello":
            case "tls_alert_after_client_hello":
            case "short_tls_response_after_client_hello":
            case "unrecognized_response_after_client_hello":
            case "unrecognized_tls_response_after_client_hello":
            case "server_hello_hmac_mismatch":
            case "faketls_not_mtproxy_response":
            case "faketls_no_server_hello_terminal":
            case "faketls_server_closed_terminal":
            case "background_handshake_aborted":
            case "handshake_profiles_exhausted":
            case "mtproxy_packet_sent_no_response":
            case "post_handshake_no_appdata":
            case "dropped_early_after_appdata":
            case "dropped_after_appdata":
                return KIND_FAILURE;
            default:
                return KIND_FAILURE;
        }
    }

    // Java-side endpoint key scope: endpoint_key from the contract with
    // explicit java_key_scope overrides (waiting_tcp, unknown_fail).
    // Pass a ProxyCheckDiagnostics.normalize()d phase.
    public static int phaseKeyScope(String phase) {
        if (phase == null) {
            return SCOPE_EXACT;
        }
        switch (phase) {
            case "ok":
            case "checking":
            case "cancelled":
            case "start_failed":
            case "connection_not_started":
                return SCOPE_NONE;
            case "unknown_fail":
            case "admission_queue":
            case "endpoint_cooldown":
            case "mtproxy_probe_wait":
            case "phase_adaptive_recipe":
            case "secret_domain_sanitized":
            case "connect_start":
            case "client_hello_sent":
            case "admission_hold_after_client_hello_failure":
            case "server_hello_hmac_ok":
            case "on_connected":
            case "first_tls_app_sent":
            case "first_mtproxy_packet_sent":
            case "first_tls_app_recv":
            case "first_mtproxy_packet_recv":
            case "connecting_timeout":
            case "admission_timeout":
            case "endpoint_cooldown_timeout":
            case "mtproxy_probe_wait_timeout":
            case "secret_parse_invalid_domain_control_char":
            case "secret_parse_invalid_domain":
            case "true_client_hello_timeout":
            case "faketls_server_hello_wait_timeout":
            case "server_closed_after_client_hello":
            case "client_hello_sent_no_server_hello":
            case "tls_alert_after_client_hello":
            case "short_tls_response_after_client_hello":
            case "unrecognized_response_after_client_hello":
            case "unrecognized_tls_response_after_client_hello":
            case "server_hello_hmac_mismatch":
            case "faketls_not_mtproxy_response":
            case "faketls_no_server_hello_terminal":
            case "faketls_server_closed_terminal":
            case "background_handshake_aborted":
            case "handshake_profiles_exhausted":
            case "mtproxy_packet_sent_no_response":
            case "post_handshake_no_appdata":
            case "dropped_after_appdata":
            case "shadowed_socket_failure":
            case "ignored_cancelled_generation":
                return SCOPE_EXACT;
            case "tcp_connect_gate":
            case "dns_coalesce_wait":
            case "dns_cache_hit":
            case "dns_cache_store":
            case "host_resolve_start":
            case "socket_connect_start":
            case "socket_connected":
            case "waiting_tcp":
            case "dns_coalesce_timeout":
            case "dns_negative_cache_hit":
            case "dns_blocked_zero_address":
            case "host_resolve_failed":
            case "host_resolve_timeout":
            case "tcp_connect_gate_timeout":
            case "tcp_not_connected":
            case "tcp_connection_refused":
            case "tcp_connect_timeout":
            case "tcp_connected_no_pong":
            case "network_block_suspected":
            case "dropped_early_after_appdata":
                return SCOPE_NETWORK;
            default:
                return SCOPE_EXACT;
        }
    }

    // Java scheduler ACTION_BACKOFF eligibility: the rotation flag with
    // explicit java_backoff overrides (unknown_fail paces retries
    // without rotating).
    // Pass a ProxyCheckDiagnostics.normalize()d phase.
    public static boolean javaBackoff(String phase) {
        if (phase == null) {
            return false;
        }
        switch (phase) {
            case "unknown_fail":
            case "connecting_timeout":
            case "host_resolve_failed":
            case "host_resolve_timeout":
            case "tcp_not_connected":
            case "tcp_connection_refused":
            case "tcp_connect_timeout":
            case "tcp_connected_no_pong":
            case "network_block_suspected":
            case "secret_parse_invalid_domain_control_char":
            case "secret_parse_invalid_domain":
            case "faketls_not_mtproxy_response":
            case "faketls_no_server_hello_terminal":
            case "faketls_server_closed_terminal":
            case "handshake_profiles_exhausted":
            case "mtproxy_packet_sent_no_response":
            case "post_handshake_no_appdata":
            case "dropped_early_after_appdata":
                return true;
            default:
                return false;
        }
    }

    // Rotation-eligible failures (rotation=True in the contract).
    // Pass a ProxyCheckDiagnostics.normalize()d phase.
    public static boolean javaRotate(String phase) {
        if (phase == null) {
            return false;
        }
        switch (phase) {
            case "connecting_timeout":
            case "host_resolve_failed":
            case "host_resolve_timeout":
            case "tcp_not_connected":
            case "tcp_connection_refused":
            case "tcp_connect_timeout":
            case "tcp_connected_no_pong":
            case "network_block_suspected":
            case "secret_parse_invalid_domain_control_char":
            case "secret_parse_invalid_domain":
            case "faketls_not_mtproxy_response":
            case "faketls_no_server_hello_terminal":
            case "faketls_server_closed_terminal":
            case "handshake_profiles_exhausted":
            case "mtproxy_packet_sent_no_response":
            case "post_handshake_no_appdata":
            case "dropped_early_after_appdata":
                return true;
            default:
                return false;
        }
    }
}
